# Generated by Django 2.2 on 2019-07-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculetar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('Ammount', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='hotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=30)),
                ('std', models.DateTimeField()),
                ('end', models.DateField()),
                ('Room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('gen', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('Repassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
