# Generated by Django 2.2 on 2019-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gml', models.CharField(max_length=30)),
                ('psw', models.CharField(max_length=30)),
            ],
        ),
    ]
